FROM golang:1.20.1 as base

FROM  base as dev

RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

RUN apt-get update && \
    apt-get install -y unzip

WORKDIR /app
CMD ["air"]